---
 - name: create a folders and files in db
   hosts: all

   tasks:
     - name: create a folder
       file:
         path: /home/ubuntu/happy
         state: directory
     - name: create a file inside the folder
       file:
         path: /home/ubuntu/happy/file.txt
         state: touch
     - name: paste the content in file
       copy:
         dest: /home/ubuntu/happy/file.txt
         content: "Success, playbook is working.."
